- src/components/Tx/History/TxHistoryList.jsx
- src/components/Tx/History/TxHistoryListEntry.jsx
- src/components/Tx/SendTx/FeeSelector.jsx
- src/components/Tx/SendTx/FormSendTx.jsx
- src/components/Tx/SendTx/FormSubmitTx.jsx
- src/components/Tx/SendTx/TxParties.jsx
- src/components/Tx/SendTx/index.js
- src/components/index.js
- src/i18n/index.js
- src/lib/util.js
- src/stories/3.Tx.stories.jsx
TxHistory refactoring
add SendTx draft
> Mist ui react migration

- src/components/CreateAccount/InputPassword.jsx
- src/components/EthAddress.jsx
- src/components/Network/NetworkChooser.jsx
- src/components/Network/NodeInfo/NodeInfoDot.jsx
- src/components/Network/RPC/RpcTester.jsx
- src/components/Tools/EthConverterForm.jsx
- src/components/Widgets/Button.jsx
- src/components/Widgets/Checkbox.jsx
- src/components/Widgets/ConverterForm.jsx
- src/components/Widgets/ValidatedField.jsx
- Establishes some component patterns (proptypes, defaultProps, component layout, etc)
- Implements the pattern on Button, Checkbox, ValidatedField, EthAddress
- Starts the pattern on NodeInfoDot, while walking through it with @ryanio 
- Pushing up now to give @ryanio a starting point.
- Component checklist coming soon.
> fix: cleanup

- package.json
- src/components/Network/NodeInfo/NodeInfo.jsx
- src/components/Network/NodeInfo/NodeInfoBox.jsx
- src/components/Network/NodeInfo/NodeInfoDot.jsx
- src/stories/6.network.stories.jsx
- yarn.lock
* Added prop structure
* Added more story states
ToDo:
* Styling
Please give the code a brief look and let me know if I'm generally moving in the right direction!
> WIP Node Info component

- src/components/Network/NodeInfo/NewBlockEvery3s.jsx
- src/components/Network/NodeInfo/NodeInfo.jsx
- src/components/Network/NodeInfo/NodeInfo.scss
- src/components/Network/NodeInfo/NodeInfoBox.jsx
- src/components/Network/NodeInfo/NodeInfoDot.jsx
- src/stories/6.network.stories.jsx
Applies a pulse and live updating behavior for the blockNumber.
Next I will try to tackle moving all the CSS from the scss file to styled-components and getting icons working
> Apply pulse behavior with NewBlockEvery3s component

- src/components/Identicon.jsx
- src/components/Wallet/AccountItem.jsx
- src/components/Wallet/TokenListForItem.jsx
- src/components/index.js
- src/stories/5.wallet.stories.jsx
Introduces the wallet component `AccountItem`. Closes #58.
- AccountList component coming next, which needs to format some data for this component.
- We should probably introduce the font into this lib?
> fix: introduces AccountItem wallet component

- .eslintrc.js
- src/components/CreateAccount/InputPassword.jsx
- src/components/Network/NetworkChooser.jsx
- src/components/Widgets/Form/FileChooser.jsx
- src/components/Widgets/Form/Input.jsx
- src/components/Widgets/Form/RadioButton.jsx
- src/components/Widgets/Form/Select.jsx
- src/components/Widgets/Form/TextArea.jsx
- src/components/Widgets/Form/ValidatedField.jsx
- src/components/index.js
- src/stories/1.index.stories.jsx
add a draft for a set of Form components
Input, FileChooser, TextArea, Select
even if we decide to use some other UI framework for this task it is a good idea to wrap them as it was done in the Select component.
This is only an incomplete draft
> feat: add Form widgets

- src/components/Identicon.jsx
- src/components/Wallet/TokenListForItem.jsx
- src/stories/1.index.stories.jsx
Updates smallest `Identicon` size name from `token` to `nano`. Closes #63.
> fix: nano Identicon size

- src/components/Wallet/AccountItem.jsx
- src/components/Wallet/AccountList.jsx
- src/components/index.js
- src/stories/3.Tx.stories.jsx
- src/stories/5.wallet.stories.jsx
- Introduces `AccountList`
- Some styling tbd (hard code in some margin for each AccountItem or allow some passthrough?)
> fix: introduces AccountList

- src/components/Wallet/NetworkStatus.jsx
- src/components/index.js
- src/stories/5.wallet.stories.jsx
Introduces `NetworkStatus`. Closes #71.
Small redesign to stack the status values.
> fix: introduces NetworkStatus

- package.json
- src/components/Widgets/Form/AddressSelect.jsx
- src/components/index.js
- src/stories/1.index.stories.jsx
- src/util/helpers.js
- yarn.lock
- Introduces `AddressSelect` component (Closes #79)
- @kielbarry got it most of the way there 💪 This finishes off v1. (Closes #88)
> feat: AddressSelect component

- src/components/CreateAccount/InputPassword.jsx
- src/components/CreateAccount/InputPassword.scss
Hi, 
I want to contribute to the migration to styled-components.
> ADD styled-components to InputPassword

- src/components/Widgets/WalletButton.jsx
- src/components/index.js
- src/stories/1.index.stories.jsx
- yarn.lock
WalletButton component for user actions.
Actions such as routing or modal displays left to the property onClick.
No.
> New wallet button

- README.md
- package.json
- src/components/Wallet/TokenCard.jsx
- src/components/index.js
- src/stories/5.wallet.stories.jsx
- yarn.lock
- introduces `TokenCard` component (Closes #87)
[geopattern](https://github.com/btmills/geopattern) - for card backgrounds
> feat: introduces TokenCard

- src/components/CreateAccount/FormCreateAccount.jsx
- src/components/CreateAccount/FormCreateAccount.scss
ADD styled-components to FormCreateAccount
> ADD styled-components to FormCreateAccount

- src/components/Tx/SendTx/CurrencySelect.jsx
- src/components/Tx/SendTx/TxDescription.jsx
- src/stories/3.Tx.stories.jsx
- simplifies API for CurrencySelector
- fixes broken styles
- additional refactoring
Too quick on the draw merging in the first PR.
> fix: CurrencySelect refactor

- src/components/Tx/SendTx/TxDescription.jsx
- src/stories/3.Tx.stories.jsx
Fixes production build for Tx stories (Closes #103)
Components index is lazy loaded and not available by the time of rendering?
> fix: prod build bug

- src/components/Network/NetworkChooser.jsx
- src/components/Network/NodeSettings/NodeSettings.jsx
- src/components/Network/NodeSettings/NodeSettingsForm.jsx
- src/components/Network/NodeSettings/NodeSettingsStorybookContainer.jsx
- src/components/Network/NodeSettings/index.js
- src/components/index.js
- src/stories/6.network.stories.jsx
This PR adds a NodeSettings component into Storybook:
> feat: NodeSettings

- .storybook/config.js
- .storybook/webpack.config.js
- src/components/CreateAccount/FormCreateAccount.jsx
- src/components/Network/NodeInfo/NodeInfo.jsx
- src/components/Tools/EthValidatedField.jsx
- src/components/Tx/SendTx/SendTxForm.jsx
- src/components/Tx/SendTx/SubmitTxForm.jsx
- src/components/Tx/SendTx/TxDescription.jsx
- src/components/Tx/SendTx/TxDescription/SendEther.jsx
- src/components/Tx/SendTx/TxParty.jsx
- src/components/Tx/TxHistory/TxEntry.jsx
- src/components/Wallet/AccountItem.jsx
- src/components/Wallet/AccountList.jsx
- src/components/Wallet/TokenCard.jsx
- src/components/Wallet/TokenListForItem.jsx
- src/components/Widgets/AnimatedIcons/Cross.jsx
- src/components/Widgets/Button.jsx
- src/components/Widgets/ConverterForm.jsx
- src/components/Widgets/Form/AddressInput.jsx
- src/components/Widgets/Form/Select.jsx
- src/components/Widgets/Form/ValidatedField.jsx
- src/components/Widgets/WalletButton.jsx
- src/stories/1.index.stories.jsx
- src/stories/6.network.stories.jsx
- webpack.prod.config.js
misc cleanup:
- refactors imports from component index file
- prettier applied to storybook config
- displayNames added back
> fix: import cleanup

- README.md
- docs/CONTRIBUTING.md
Adds contribution guidelines and cleans the README a bit.
A version of this document is going in all the Mist repos.
> fix: introduces contribution guidelines

- .circleci/config.yml
- package.json
- src/components/Widgets/Checkbox.jsx
- Has CircleCI perform linting, so it can remind people to use their linter for me.
- Clarifies some lint scripts.
- Sneaks in a line of css to fix a broken checkbox on Firefox.
> chore: lint in CI

- .storybook/preview-head.html
- package.json
- src/components/CreateAccount/FormCreateAccount.jsx
- src/components/Network/NodeSettings/NodeSettingsForm.jsx
- src/components/Tx/SendTx/SubmitTxForm.jsx
- src/components/Tx/SendTx/TxDescription.jsx
- src/components/Widgets/Button.jsx
- src/components/Widgets/Form/AddressInput.jsx
- src/components/Widgets/Form/Input.jsx
- src/stories/1.index.stories.jsx
- yarn.lock
- Out with grommet, in with material-ui.
- Updates Button, Input, and AddressInput components.
Some small component API changes to accommodate material-ui features. I believe they're intuitive, but see usage in the stories and let me know!
https://material-ui.com
> chore: introduces material-ui

- src/components/Widgets/Form/Progress.jsx
- src/components/index.js
- src/stories/1.index.stories.jsx
Introduces material-ui progress components
Still weighing best route for sharing themes and still allowing for customization. Some wrinkles, e.g. our button secondary color is white, but if applied universally, would cause other components to look terrible/invisible.
> fix: mui progress

- src/components/Tx/SendTx/FeeSelector.jsx
- src/components/Widgets/AnimatedIcons/Spinner.jsx
- src/stories/1.index.stories.jsx
Replaces existing spinner with material-ui's. Closes https://github.com/ethereum/mist-shell/issues/53.
Unsure of appropriate secondary color, so went with white for now.
> fix: mui spinner

- package.json
- webpack.prod.config.js
- yarn.lock
deactivate mangling during minification
creates config (optimization) parity with storybook build
> fix: webpack - deactivate mangling

- README.md
- src/stories/1.index.stories.jsx
Cleans up some story structure, removes unnecessary hierarchy, etc.
> chore: cleans up story structure
