src/components/Identicon.jsx
src/stories/1.index.stories.jsx

- styles via SC
- handles cases: tiny, small, medium, large (as seen in Mist)
- strips out optimizations for now (e.g. caching, jazzicons)
- closes #1

fix: brings Identicon to parity with Mist

---

src/components/EthAddress.jsx
src/stories/1.index.stories.jsx

- Simplifies EthAddress to props: address, short, onClick
- Closes #22 
Jumped on a screenshare with @kielbarry to talk through usage within the wallet. We agreed that the first iteration shouldn't couple styling or identicons. Will continue to evaluate once pulled into the repo.

fix: updates EthAddress with wallet feedback

---

src/components/EthAddress.jsx

This PR adds a classes props that allows for so implementors can add custom class names, and adds a sanity check for address prop inputs.
For example, in my app, a contract pending deployment uses the contract address field which remains undefined until deployment is confirmed. Short = false prevents .split() from being performed on 'undefined' props.

praha: sanitycheck for missing props and adding custom classes

---

src/components/Identicon.jsx

This PR adds some error handling that can occur in my app, adds a tooltip that exists in the browser wallet, and calls identiconData function once.
Note: The classes implementation I have added is not the best solution, as I believe the classes props are applied before the styles of the StyledSpan.

praha: some sanity checks, title tooltip, added passable classes et al

---

README.md
src/components/Identicon.jsx
src/i18n/index.js
src/stories/1.index.stories.jsx

- Cleans up the `Identicon` component syntax
- Styles applied for 'medium' size by deault
- **Breaking change** - API calls for `address` instead of `seed` now

fix: clean up identicon

---

.github/PULL_REQUEST_TEMPLATE.md
src/components/CreateAccount/FormCreateAccount.jsx
src/components/CreateAccount/InputPassword.jsx
src/components/EthAddress.jsx
src/components/Identicon.jsx
src/components/Network/NetworkChooser.jsx
src/components/Tools/EthConverterForm.jsx
src/components/Tools/EthValidatedField.jsx
src/components/Tx/History/TxHistoryList.jsx
src/components/Tx/History/TxHistoryListEntry.jsx
src/components/Tx/SendTx/FeeSelector.jsx
src/components/Tx/SendTx/FormSendTx.jsx
src/components/Tx/SendTx/FormSubmitTx.jsx
src/components/Tx/SendTx/TxDescription.jsx
src/components/Tx/SendTx/TxParties.jsx
src/components/Widgets/AnimatedIcons/AnimatedCross.jsx
src/components/Widgets/AnimatedIcons/Checkmark.jsx
src/components/Widgets/Button.jsx
src/components/Widgets/Checkbox.jsx
src/components/Widgets/ConverterForm.jsx
src/components/Widgets/LoadingAnimations.jsx
src/components/Widgets/ValidatedField.jsx
src/stories/1.index.stories.jsx

- Adds `displayName`s for everything
- Standardizes export statements
- Refactors some of the remaining funcs to follow the component patterns
- Adds a PR template
- I think this finally: closes #33, closes #32, closes #31 
- Skips over Network components as to avoid  conflicts with @ryanio's work
- A draft of the [style checklist](https://gist.github.com/marcgarreau/a27e0d6d24305f4b79170df97a10e88b)

fix: adds displayNames, other standardizations

---

deploy.sh

Currently, the deploy process creates two commits with separate `git push`. This PR removes one of those, so CircleCI does not get flooded with skipped tasks.

chore: update deploy script

---

.eslintrc.js
src/components/Tx/SendTx/TxDescription.jsx
src/components/Tx/SendTx/TxDescription/DeployContract.jsx
src/components/Tx/SendTx/TxDescription/FunctionExecution.jsx
src/components/Tx/SendTx/TxDescription/SendEther.jsx
src/components/Tx/SendTx/TxDescription/TokenTransfer.jsx
src/lib/util.js
src/stories/3.Tx.stories.jsx
src/util/formatters.js

- Introduces four tx description types: send eth, send tokens, execute function, deploy contract.
Getting this out the door to turn attention to the wallet. TxDescription still needs more love before its said and done. The "show details" section remains, and the component API is still up for debate (e.g. should TxDescription accept a prop of `txType` which is one of 'sendEth', 'deployContract', etc. instead of reaching that conclusion internally based on props)
n/a

fix: introduces tx description states

---

src/components/Tx/SendTx/FeeSelector.jsx
src/components/Widgets/AnimatedIcons/Spinner.jsx
src/components/Widgets/Button.jsx
src/stories/1.index.stories.jsx

Adds loading state to `Button`; this replaces the content of the button with a `Spinner` component and applies `disabled` styling. Closes #60.
- This doesn't address Philipp's other Button styling critiques about resizing and active states. That'll be a follow-on PR after playing with some styling options.
- I used a min-width to prevent the button from shrinking too small after it changes to a loading state. Open to feedback on that UX.
n/a

fix: adds loading state to Button

---

src/components/Wallet/NavbarItem.jsx
src/components/index.js
src/stories/5.wallet.stories.jsx

Introduces `NavbarItem` component. Closes #67.
Opted for a more explicit API rather than one that hides the font-awesome details. Pros: create new NavbarItems without updating this lib. Cons: need to know the icon name when writing the components.

fix: introduces NavbarItem

---

.storybook/preview-head.html
README.md
package.json
src/components/Network/NodeInfo/NodeInfoBox.jsx
src/components/Wallet/AccountItem.jsx
src/components/Wallet/NavbarItem.jsx
src/components/Wallet/NetworkStatus.jsx
src/lib/util.js
yarn.lock

- introduces bignumber.js for proper decimal handling (Closes #75)
- standardizes fontawesome icon usage
- adds font to storybook (not the components themselves)
- style tweaks notices while working on the wallet
- the bignumber lib can be swapped out if we decide to handle this differently in the future. I saw this as the quickest way forward.
- `preview-head.html` is a storybook-specific file/feature to introduce custom scripts to the storybook server.
- I believe the `library` function in fontawesome is best used when all icons are imported in some top-level component. Since we have a modular component lib, I think it makes sense to skip this convenience function.
[bignumber.js](http://mikemcl.github.io/bignumber.js/) -- handling decimal arithmetic 
lacking decimal logic before:
after:

fix: cleanup for wallet components

---

README.md
package.json
src/components/Identicon.jsx
src/components/Wallet/AccountItem.jsx
src/components/Widgets/AnimatedIcons/AnimatedCross.jsx
src/components/Widgets/Form/AddressInput.jsx
src/components/Widgets/Form/Input.jsx
src/components/index.js
src/index.js
src/lib/util.js
src/stories/1.index.stories.jsx
yarn.lock

- Introduces `AddressInput` wallet component; Closes #78 
- Makes component lib utils available for import: e.g. `import { AddressInput, utils } from 'ethereum-react-components'`
- Adds style extensibility to `Identicon` + `Cross` components for positioning within `AddressInput`
- Removes `styled-jsx` dep

feat: introduces AddressInput

---

src/components/Wallet/NavbarItem.jsx
src/components/Wallet/NetworkStatus.jsx
src/components/Wallet/Notification.jsx
src/components/Widgets/Form/AddressInput.jsx
src/components/index.js
src/lib/util.js
src/stories/5.wallet.stories.jsx

- Introduces a `Notification` component (Closes #80)
- Cleans up some empty state for `NetworkStatus`
- The animation is simple CSS (within styled-components)
- Notification data, in the case of the wallet, resides in the Redux store. For that reason, the `Notification` component makes sense to reside in the component lib, but `Notifications` (plural) lives in the wallet app, so that it can flush out the notification data after the 8 seconds (or other configurable) dismiss delay.
- This includes a warning/yellow color. Future iteration could introduce a `type` key which tweaks colors for error, success, etc.
multiple example usage in wallet. low frame rate, for no extra charge:

feat: Notification

---

package.json
src/components/Wallet/NavbarBalance.jsx
src/components/Widgets/AnimatedIcons/Spinner.jsx
src/components/Widgets/Button.jsx
src/stories/1.index.stories.jsx

Lots of small cleanup.
- Fixes the lint-staged precommit script. I thought the tasks were synchronous, but they sure aren't.
- Fixes a couple outstanding lints.
- Spinner
- Brings css into styled-components
- Makes predictable inline-block sizes (vs. unwieldy absolute positioning)
- Button
- Shrunk the size; looked fine in storybook, but when imported in mist-ui it blew up and looked awful.
- Uppercases text
- Loading state preserves btn text in addition to showing spinner. Spinner gets floated to the right. Don't think its a finished product yet, but it's slightly better. (Requested by @PhilippLgh.)
- If not aware, @sarovin made a nice PR that introduced `stylelint`. That is new to the precommit pipeline.
- Tested mist-ui via npm link. See screenshot below for more sane padding and …

fix: btn and spinner configs

---

src/components/Widgets/Form/Input.jsx
src/components/Widgets/Form/TextArea.jsx
src/stories/1.index.stories.jsx

- Introduces material-ui TextArea
- Adds AddressInput story cleanup left behind in last PR
In mui-terms, textarea is just an input field with a `multiline` prop.

fix: mui textarea

---

src/components/Grid.jsx
src/components/index.js
src/stories/1.index.stories.jsx

- Introduces material-ui's Grid component. Closes https://github.com/ethereum/mist-shell/issues/57.
- Organizes/alphabetizes some imports
This grid is easy to use:
- define a container: 
- `<Grid container></Grid>`
- set items within it: 
- `<Grid item>...</Grid>`
- set sizes (a fraction of 12) on each item. multiple breakpoints okay: 
- `<Grid item sm={6} xs={12}>...</Grid>`

chore: add mui grid

---

src/components/Widgets/AnimatedIcons/Spinner.jsx
src/components/Widgets/Button.jsx
src/components/Widgets/Form/Progress.jsx
src/components/Widgets/Form/Select.jsx
src/stories/1.index.stories.jsx

- Remove material-ui theme from individual components to allow for app-wide themes in mist-ui.
- Storybook still has desired theme; it's implemented in the stories now.

fix: remove theme from lib

---

src/components/Widgets/Button.jsx
src/stories/1.index.stories.jsx

Cleans up the Button API.
- Resolves the warning: `Received 'false' for a non-boolean attribute 'secondary'`
- Gets closer to the material-ui API, so there should be fewer surprises for devs already comfortable with material-ui.
- API changes slightly: instead of 
`<Button secondary>Click Me</Button>`
replace with:
`<Button color="secondary">Click Me</Button>`

fix: btn API

---

package.json
webpack.prod.config.js

Swaps `file-loader` for `url-loader` to bundle image assets via webpack.
- `url-loader` inlines base64 URLs
- i don't think it supports svgs, but we don't package any of those for now.
`url-loader` (already installed as a dep of storybook, though)
test app - before:
after:

fix: url-loader for imgs

---

CONTRIBUTING.md
README.md

- Removes Mist references.
- Moves CONTRIBUTING doc outside of messy storybook docs dir.
- Small cleanup
Testing the netlify preview builder.

docs: updates Mist references, etc
